spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true

  elasticsearch:
    uris: 133.186.153.181:9200
    connection-timeout: 30

server:
  port: 1090

logging:
  level:
    root: info
    org.springframework.data.elasticsearch.client.WIRE: error