spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true

server:
  port: 1090

# TODO 2: yml 파일에 ElasticSearch Server 의 Host, Port, url 지정
elasticsearch:
  host: 127.0.0.1
  port: 9200
  url: http://localhost:9200

logging:
  level:
    root: info
    org.springframework.data.elasticsearch.client.WIRE: trace