spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true

# TODO 1-1: yml 파일에 엘라스틱 서치 서버 연동 설정
  elasticsearch:
    uris: 127.0.0.1:9200
    connection-timeout: 30
    password: 123456
    username: elastic

server:
  port: 1090

logging:
  level:
    root: info
    org.springframework.data.elasticsearch.client.WIRE: error